@extends('layouts.admin')
@section('title', 'Edit Notification Template | '.$marketplaceName)
@section('page_title', 'Edit Notification Template')
@section('content')
<div class="row g-3"><div class="col-xl-8">
<div class="card"><div class="card-header"><h5 class="mb-0">{{ $event->label }}</h5></div><div class="card-body">
    <dl class="row mb-3"><dt class="col-sm-3">Event Key</dt><dd class="col-sm-9"><code>{{ $event->key }}</code></dd><dt class="col-sm-3">Channel</dt><dd class="col-sm-9"><span class="badge bg-primary bg-opacity-10 text-primary">{{ ucfirst($template->channel) }}</span></dd><dt class="col-sm-3">Recipient</dt><dd class="col-sm-9">{{ ucfirst($event->audience) }}</dd><dt class="col-sm-3">Rule</dt><dd class="col-sm-9">{{ ucfirst($rule) }} @if($rule === 'mandatory') 🔒 Required notification @endif</dd><dt class="col-sm-3">Default</dt><dd class="col-sm-9">{{ $event->defaultEnabled($template->channel) ? 'ON' : 'OFF' }}</dd></dl>
    <form method="POST" action="{{ route('admin.notification-templates.update', $template) }}">@csrf @method('PUT')
        @if($template->channel === 'email')<div class="mb-3"><label class="form-label">Subject</label><input name="subject" value="{{ old('subject', $template->subject) }}" class="form-control @error('subject') is-invalid @enderror">@error('subject')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>@endif
        <div class="mb-3"><label class="form-label">Body</label><textarea name="body" rows="10" class="form-control @error('body') is-invalid @enderror">{{ old('body', $template->body) }}</textarea>@error('body')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        @if($template->channel === 'email')<div class="row g-3"><div class="col-md-6"><label class="form-label">CC</label><textarea name="email_cc" rows="2" class="form-control @error('email_cc') is-invalid @enderror" placeholder="manager@example.com, accounts@example.com">{{ old('email_cc', $emailCc) }}</textarea><div class="form-text">Optional. These addresses receive a visible copy whenever this email notification is sent.</div>@error('email_cc')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label">BCC</label><textarea name="email_bcc" rows="2" class="form-control @error('email_bcc') is-invalid @enderror" placeholder="manager@example.com, accounts@example.com">{{ old('email_bcc', $emailBcc) }}</textarea><div class="form-text">Optional. These addresses receive a hidden copy whenever this email notification is sent.</div>@error('email_bcc')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>@endif
        <div class="form-check mt-3"><input type="hidden" name="is_active" value="0"><input id="is_active" name="is_active" value="1" type="checkbox" class="form-check-input" @checked(old('is_active', $template->is_active)) @disabled($rule === 'mandatory')><label for="is_active" class="form-check-label">Active @if($rule === 'mandatory')(locked by mandatory policy)@endif</label></div>
        <div class="d-flex gap-2 mt-3"><button class="btn btn-primary">Save Template</button>@if($template->channel === 'email')<button class="btn btn-outline-primary" formaction="{{ route('admin.notification-templates.preview', $template) }}" formmethod="POST">Preview Email</button>@endif<a class="btn btn-light" href="{{ route('admin.notification-templates.index') }}">Back</a></div>
    </form>
</div></div></div>
<div class="col-xl-4"><div class="card"><div class="card-header"><h5 class="mb-0">Available Variables</h5></div><div class="card-body"><p class="text-muted">Only these controlled placeholders are accepted.</p><div class="d-flex flex-wrap gap-2">@foreach($template->variables ?? [] as $variable)<code>&#123;&#123; {{ $variable }} &#125;&#125;</code>@endforeach</div></div></div></div></div>
@endsection
