<div>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f0f8f4;border-radius:8px;margin-bottom:20px">
        <tr><td style="padding:20px;vertical-align:top;width:42%"><div style="font-size:12px;font-weight:700;letter-spacing:.08em;color:#278753;text-transform:uppercase">{{ $orderEmail['heading'] }}</div><div style="font-size:22px;font-weight:700;margin-top:7px">{{ $orderEmail['order_number'] }}</div><div style="font-size:12px;color:#68707b;margin-top:6px">{{ $orderEmail['placed_at'] }}</div></td><td style="padding:20px;border-left:1px solid #dfe9e3;font-size:14px;line-height:1.55">@if($orderEmail['greeting'])<strong>{{ $orderEmail['greeting'] }}</strong><br><br>@endif{!! nl2br(e($orderEmail['intro'])) !!}</td></tr>
    </table>

    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #e1e5e9;border-radius:7px;border-collapse:separate;margin-bottom:18px;font-size:13px">
        <tr><td colspan="4" style="padding:11px 14px;background:#f7f8fa;font-weight:700;letter-spacing:.06em">ORDER DETAILS</td></tr>
        <tr><td style="padding:10px 14px;color:#68707b">Order Number</td><td style="padding:10px 14px;font-weight:600">{{ $orderEmail['order_number'] }}</td><td style="padding:10px 14px;color:#68707b">Payment Method</td><td style="padding:10px 14px;font-weight:600">{{ $orderEmail['payment_method_label'] }}</td></tr>
        <tr><td style="padding:10px 14px;color:#68707b">Shop</td><td style="padding:10px 14px;font-weight:600">{{ $orderEmail['shop_name'] }}</td><td style="padding:10px 14px;color:#68707b">Payment Status</td><td style="padding:10px 14px;font-weight:600">{{ $orderEmail['payment_status_label'] }}</td></tr>
        <tr><td style="padding:10px 14px;color:#68707b">Order Status</td><td style="padding:10px 14px;font-weight:600">{{ $orderEmail['order_status_label'] }}</td><td style="padding:10px 14px;color:#68707b">Fulfilment</td><td style="padding:10px 14px;font-weight:600">{{ $orderEmail['fulfilment_label'] }}</td></tr>
    </table>

    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:18px;font-size:13px"><tr>
        <td width="49%" style="border:1px solid #e1e5e9;vertical-align:top"><div style="padding:11px 14px;background:#f7f8fa;font-weight:700">BILLING DETAILS</div><div style="padding:12px 14px;line-height:1.55">@forelse($orderEmail['billing_address'] as $line)<div>{{ $line }}</div>@empty<div style="color:#68707b">Not provided</div>@endforelse</div></td>
        <td width="2%"></td>
        <td width="49%" style="border:1px solid #e1e5e9;vertical-align:top"><div style="padding:11px 14px;background:#f7f8fa;font-weight:700">{{ $orderEmail['fulfilment_label'] === 'Delivery' ? 'DELIVERY DETAILS' : 'PICKUP DETAILS' }}</div><div style="padding:12px 14px;line-height:1.55">@if($orderEmail['fulfilment_label'] === 'Delivery') @foreach($orderEmail['delivery_address'] as $line)<div>{{ $line }}</div>@endforeach @else @foreach($orderEmail['pickup_details'] as $line)<div>{{ $line }}</div>@endforeach <div style="margin-top:8px;color:#68707b">The shop will notify the customer when the order is ready for pickup.</div> @endif</div></td>
    </tr></table>

    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #e1e5e9;border-collapse:collapse;margin-bottom:18px;font-size:12px">
        <tr><td colspan="5" style="padding:11px 14px;background:#f7f8fa;font-weight:700;letter-spacing:.06em">ORDER ITEMS</td></tr>
        <tr style="background:#fafbfc;color:#4f5965"><th align="left" style="padding:9px">Product</th><th align="left" style="padding:9px">Variant / Model</th><th align="center" style="padding:9px">Qty</th><th align="right" style="padding:9px">Price</th><th align="right" style="padding:9px">Total</th></tr>
        @foreach($orderEmail['items'] as $item)<tr><td style="padding:10px 9px;border-top:1px solid #e6e8eb"><strong>{{ $item['name'] }}</strong>@if($item['is_gift'])<br><span style="color:#237a4b;font-weight:700">FREE GIFT</span>@endif</td><td style="padding:10px 9px;border-top:1px solid #e6e8eb">{{ $item['variant'] }}@if($item['sku'] && $item['sku'] !== $item['variant'])<br><span style="color:#68707b">{{ $item['sku'] }}</span>@endif</td><td align="center" style="padding:10px 9px;border-top:1px solid #e6e8eb">{{ $item['quantity'] }}</td><td align="right" style="padding:10px 9px;border-top:1px solid #e6e8eb;white-space:nowrap">{{ $item['unit_price'] }}</td><td align="right" style="padding:10px 9px;border-top:1px solid #e6e8eb;white-space:nowrap;font-weight:600">{{ $item['line_total'] }}</td></tr>@endforeach
    </table>

    @if($orderEmail['promotions'])<div style="padding:11px 14px;background:#f0f7f3;color:#245f3d;font-size:12px;margin-bottom:18px">@foreach($orderEmail['promotions'] as $promotion)<div><strong>Offer: {{ $promotion['name'] }}</strong>@if($promotion['coupon_code']) &nbsp; Coupon: {{ $promotion['coupon_code'] }}@endif</div>@endforeach</div>@endif

    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #e1e5e9;border-collapse:collapse;font-size:13px"><tr><td colspan="2" style="padding:11px 14px;background:#f7f8fa;font-weight:700;letter-spacing:.06em">ORDER TOTALS</td></tr>@foreach($orderEmail['totals'] as $total)<tr @if($total['prominent']) style="background:#eef8f2;color:#116c3c;font-size:17px" @endif><td style="padding:9px 14px;border-top:{{ $total['prominent'] ? '2px solid #cfe4d7' : '1px solid #edf0f2' }};font-weight:{{ $total['prominent'] ? '700' : '400' }}">{{ $total['title'] }}</td><td align="right" style="padding:9px 14px;border-top:{{ $total['prominent'] ? '2px solid #cfe4d7' : '1px solid #edf0f2' }};font-weight:{{ $total['prominent'] ? '700' : '600' }}">{{ $total['amount'] }}</td></tr>@endforeach</table>

    @if($orderEmail['cta_url'])<div style="margin-top:24px;text-align:center"><a href="{{ $orderEmail['cta_url'] }}" style="display:inline-block;padding:13px 24px;background:#172033;color:#fff;text-decoration:none;border-radius:6px;font-size:13px;font-weight:700">{{ $orderEmail['cta_label'] }}</a><div style="margin:12px auto 0;max-width:560px;color:#68707b;font-size:11px;line-height:1.5">Button not working? Copy and paste this link into your browser:<br><a href="{{ $orderEmail['cta_url'] }}" style="color:#68707b;text-decoration:underline;overflow-wrap:anywhere;word-break:break-word">{{ $orderEmail['cta_url'] }}</a></div>@if($orderEmail['follow_up'])<div style="margin-top:12px;color:#68707b;font-size:12px;line-height:1.5">{!! nl2br(e($orderEmail['follow_up'])) !!}</div>@endif</div>@endif
</div>
