<?php

namespace Database\Seeders\MasterData;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductAttributeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();

        $groups = [
            [
                'name' => 'Size',
                'code' => 'size',
                'description' => 'Apparel product sizes',
                'selection_type' => 'multiple',
                'values' => [
                    'XS',
                    'S',
                    'M',
                    'L',
                    'XL',
                    'XXL',
                    '3XL',
                    '4XL',
                    '5XL',
                    '6XL',
                    'Free Size',
                    'Shoe Size 5',
                    'Shoe Size 6',
                    'Shoe Size 7',
                    'Shoe Size 8',
                    'Shoe Size 9',
                    'Shoe Size 10',
                    'Shoe Size 11',
                    'Shoe Size 12',
                ],
            ],
            [
                'name' => 'Color',
                'code' => 'color',
                'description' => 'Product colors',
                'selection_type' => 'multiple',
                'values' => [
                    'Black',
                    'White',
                    'Red',
                    'Blue',
                    'Green',
                    'Yellow',
                    'Pink',
                    'Purple',
                    'Orange',
                    'Brown',
                    'Grey',
                    'Beige',
                    'Navy',
                    'Maroon',
                    'Gold',
                    'Silver',
                    'Multicolor',
                ],
            ],
            [
                'name' => 'Material',
                'code' => 'material',
                'description' => 'Primary product materials',
                'values' => [
                    'Cotton',
                    'Polyester',
                    'Rayon',
                    'Silk',
                    'Wool',
                    'Linen',
                    'Denim',
                    'Leather',
                    'Faux Leather',
                    'Nylon',
                    'Viscose',
                    'Acrylic',
                    'Spandex',
                    'Blended',
                ],
            ],
            [
                'name' => 'Fit',
                'code' => 'fit',
                'description' => 'Apparel fit types',
                'values' => [
                    'Regular Fit',
                    'Slim Fit',
                    'Relaxed Fit',
                    'Loose Fit',
                    'Oversized Fit',
                    'Tailored Fit',
                    'Straight Fit',
                    'Skinny Fit',
                ],
            ],
            [
                'name' => 'Sleeve',
                'code' => 'sleeve',
                'description' => 'Sleeve styles and lengths',
                'values' => [
                    'Sleeveless',
                    'Short Sleeve',
                    'Half Sleeve',
                    'Three Quarter Sleeve',
                    'Full Sleeve',
                    'Cap Sleeve',
                    'Bell Sleeve',
                    'Puff Sleeve',
                    'Raglan Sleeve',
                ],
            ],
            [
                'name' => 'Neck',
                'code' => 'neck',
                'description' => 'Neckline styles',
                'values' => [
                    'Round Neck',
                    'V Neck',
                    'Collared Neck',
                    'Mandarin Collar',
                    'Boat Neck',
                    'Square Neck',
                    'Halter Neck',
                    'Scoop Neck',
                    'High Neck',
                    'Sweetheart Neck',
                ],
            ],
            [
                'name' => 'Pattern',
                'code' => 'pattern',
                'description' => 'Product patterns and prints',
                'values' => [
                    'Solid',
                    'Printed',
                    'Striped',
                    'Checked',
                    'Floral',
                    'Geometric',
                    'Embroidered',
                    'Textured',
                    'Polka Dot',
                    'Paisley',
                    'Abstract',
                ],
            ],
            [
                'name' => 'Occasion',
                'code' => 'occasion',
                'description' => 'Suitable product occasions',
                'selection_type' => 'multiple',
                'values' => [
                    'Casual',
                    'Formal',
                    'Party',
                    'Festive',
                    'Wedding',
                    'Engagement',
                    'Reception',
                    'Sangeet',
                    'Haldi',
                    'Mehendi',
                    'Work',
                    'Sports',
                    'Travel',
                    'Daily Wear',
                    'Ethnic',
                    'Puja',
                    'Gifting',
                ],
            ],
            [
                'name' => 'Festival',
                'code' => 'festival',
                'description' => 'Festival or celebration suitability',
                'selection_type' => 'multiple',
                'values' => [
                    'Diwali',
                    'Navratri',
                    'Dussehra',
                    'Raksha Bandhan',
                    'Ganesh Chaturthi',
                    'Eid',
                    'Christmas',
                    'New Year',
                    'Holi',
                    'Makar Sankranti',
                    'Pongal',
                    'Onam',
                    'Karwa Chauth',
                    'Bhai Dooj',
                    'Valentine Day',
                ],
            ],
            [
                'name' => 'Season',
                'code' => 'season',
                'description' => 'Suitable season or weather use',
                'selection_type' => 'multiple',
                'values' => [
                    'Summer',
                    'Winter',
                    'Monsoon',
                    'Spring',
                    'Autumn',
                    'All Season',
                ],
            ],
            [
                'name' => 'Style',
                'code' => 'style',
                'description' => 'Overall product style',
                'selection_type' => 'multiple',
                'values' => [
                    'Traditional',
                    'Modern',
                    'Contemporary',
                    'Minimal',
                    'Classic',
                    'Bohemian',
                    'Indo Western',
                    'Streetwear',
                    'Office Wear',
                    'Designer',
                ],
            ],
            [
                'name' => 'Length',
                'code' => 'length',
                'description' => 'Product length or garment length',
                'values' => [
                    'Crop',
                    'Waist Length',
                    'Hip Length',
                    'Knee Length',
                    'Calf Length',
                    'Ankle Length',
                    'Floor Length',
                    'Regular Length',
                    'Longline',
                ],
            ],
            [
                'name' => 'Waist Rise',
                'code' => 'waist_rise',
                'description' => 'Bottomwear waist rise',
                'values' => [
                    'Low Rise',
                    'Mid Rise',
                    'High Rise',
                    'Ultra High Rise',
                ],
            ],
            [
                'name' => 'Closure',
                'code' => 'closure',
                'description' => 'Product closure type',
                'values' => [
                    'Button',
                    'Zip',
                    'Hook',
                    'Drawstring',
                    'Elastic',
                    'Slip On',
                    'Tie Up',
                    'Velcro',
                    'No Closure',
                ],
            ],
            [
                'name' => 'Care',
                'code' => 'care',
                'description' => 'Care and wash instructions',
                'values' => [
                    'Machine Wash',
                    'Hand Wash',
                    'Dry Clean',
                    'Gentle Wash',
                    'Do Not Bleach',
                    'Warm Iron',
                    'Do Not Iron',
                ],
            ],
            [
                'name' => 'Country of Origin',
                'code' => 'country_of_origin',
                'description' => 'Manufacturing or origin country',
                'values' => [
                    'India',
                    'Imported',
                    'China',
                    'Bangladesh',
                    'Vietnam',
                    'Turkey',
                ],
            ],
            [
                'name' => 'Brand Model',
                'code' => 'brand_model',
                'description' => 'Manufacturer model or product series',
                'values' => [
                    'Standard',
                    'Pro',
                    'Plus',
                    'Max',
                    'Mini',
                    'Lite',
                    'Classic',
                    'Premium',
                ],
            ],
            [
                'name' => 'Storage',
                'code' => 'storage',
                'description' => 'Device storage capacity',
                'values' => [
                    '32 GB',
                    '64 GB',
                    '128 GB',
                    '256 GB',
                    '512 GB',
                    '1 TB',
                ],
            ],
            [
                'name' => 'RAM',
                'code' => 'ram',
                'description' => 'Device memory capacity',
                'values' => [
                    '2 GB',
                    '3 GB',
                    '4 GB',
                    '6 GB',
                    '8 GB',
                    '12 GB',
                    '16 GB',
                ],
            ],
            [
                'name' => 'Warranty',
                'code' => 'warranty',
                'description' => 'Warranty coverage period',
                'values' => [
                    'No Warranty',
                    '7 Days',
                    '30 Days',
                    '3 Months',
                    '6 Months',
                    '1 Year',
                    '2 Years',
                    '3 Years',
                ],
            ],
            [
                'name' => 'Connectivity',
                'code' => 'connectivity',
                'description' => 'Connectivity or network support',
                'selection_type' => 'multiple',
                'values' => [
                    'Bluetooth',
                    'Wi-Fi',
                    'USB',
                    'Type-C',
                    'Lightning',
                    'AUX',
                    '4G',
                    '5G',
                    'NFC',
                ],
            ],
            [
                'name' => 'Pack Size',
                'code' => 'pack_size',
                'description' => 'Pack, bundle or quantity size',
                'values' => [
                    'Single',
                    'Pack of 2',
                    'Pack of 3',
                    'Pack of 4',
                    'Pack of 5',
                    'Pack of 6',
                    'Pack of 10',
                    'Family Pack',
                    'Combo Pack',
                ],
            ],
            [
                'name' => 'Net Quantity',
                'code' => 'net_quantity',
                'description' => 'Weight, volume or count printed on pack',
                'values' => [
                    '50 g',
                    '100 g',
                    '200 g',
                    '250 g',
                    '500 g',
                    '1 kg',
                    '2 kg',
                    '100 ml',
                    '250 ml',
                    '500 ml',
                    '1 L',
                    '2 L',
                ],
            ],
            [
                'name' => 'Flavor',
                'code' => 'flavor',
                'description' => 'Taste, flavour or fragrance variant',
                'values' => [
                    'Original',
                    'Masala',
                    'Spicy',
                    'Sweet',
                    'Salted',
                    'Chocolate',
                    'Vanilla',
                    'Strawberry',
                    'Lemon',
                    'Mint',
                    'Rose',
                ],
            ],
            [
                'name' => 'Shelf Life',
                'code' => 'shelf_life',
                'description' => 'Product shelf life or expiry guidance',
                'values' => [
                    '7 Days',
                    '15 Days',
                    '1 Month',
                    '3 Months',
                    '6 Months',
                    '9 Months',
                    '12 Months',
                    '24 Months',
                ],
            ],
            [
                'name' => 'Diet Type',
                'code' => 'diet_type',
                'description' => 'Food or grocery dietary classification',
                'selection_type' => 'multiple',
                'values' => [
                    'Vegetarian',
                    'Non Vegetarian',
                    'Egg',
                    'Vegan',
                    'Jain',
                    'Gluten Free',
                    'Sugar Free',
                    'Organic',
                ],
            ],
            [
                'name' => 'Food Type',
                'code' => 'food_type',
                'description' => 'Prepared food type',
                'values' => [
                    'Beverage',
                    'Snack',
                    'Meal',
                    'Bakery',
                    'Dessert',
                    'Breakfast',
                    'Combo',
                ],
            ],
            [
                'name' => 'Spice Level',
                'code' => 'spice_level',
                'description' => 'Food spice level',
                'values' => [
                    'No Spice',
                    'Mild',
                    'Medium',
                    'Spicy',
                    'Extra Spicy',
                ],
            ],
            [
                'name' => 'Portion Size',
                'code' => 'portion_size',
                'description' => 'Serving or portion size',
                'values' => [
                    'Small',
                    'Regular',
                    'Medium',
                    'Large',
                    'Family',
                    'Single Serve',
                    'Serves 2',
                    'Serves 4',
                ],
            ],
            [
                'name' => 'Shade',
                'code' => 'shade',
                'description' => 'Cosmetic shade or tone',
                'values' => [
                    'Ivory',
                    'Natural',
                    'Beige',
                    'Sand',
                    'Caramel',
                    'Honey',
                    'Rose',
                    'Coral',
                    'Berry',
                    'Nude',
                    'Plum',
                    'Red',
                ],
            ],
            [
                'name' => 'Skin Type',
                'code' => 'skin_type',
                'description' => 'Suitable skin type',
                'selection_type' => 'multiple',
                'values' => [
                    'All Skin Types',
                    'Dry',
                    'Oily',
                    'Combination',
                    'Sensitive',
                    'Normal',
                    'Acne Prone',
                ],
            ],
            [
                'name' => 'Finish',
                'code' => 'finish',
                'description' => 'Product finish or surface result',
                'values' => [
                    'Matte',
                    'Glossy',
                    'Satin',
                    'Dewy',
                    'Natural',
                    'Metallic',
                    'Textured',
                    'Polished',
                ],
            ],
            [
                'name' => 'Form',
                'code' => 'form',
                'description' => 'Physical product form',
                'values' => [
                    'Liquid',
                    'Cream',
                    'Gel',
                    'Powder',
                    'Stick',
                    'Spray',
                    'Bar',
                    'Tablet',
                    'Capsule',
                ],
            ],
            [
                'name' => 'Dimensions',
                'code' => 'dimensions',
                'description' => 'Product size or dimensions',
                'values' => [
                    'Small',
                    'Medium',
                    'Large',
                    'Extra Large',
                    'Single',
                    'Double',
                    'Queen',
                    'King',
                    'Custom',
                ],
            ],
            [
                'name' => 'Room Type',
                'code' => 'room_type',
                'description' => 'Suitable room or placement',
                'selection_type' => 'multiple',
                'values' => [
                    'Living Room',
                    'Bedroom',
                    'Kitchen',
                    'Dining Room',
                    'Bathroom',
                    'Office',
                    'Outdoor',
                    'Kids Room',
                ],
            ],
            [
                'name' => 'Assembly Required',
                'code' => 'assembly_required',
                'description' => 'Whether assembly is required',
                'values' => [
                    'No',
                    'Yes',
                    'Basic Assembly',
                    'Professional Assembly',
                ],
            ],
            [
                'name' => 'Sport Type',
                'code' => 'sport_type',
                'description' => 'Sport or activity type',
                'selection_type' => 'multiple',
                'values' => [
                    'Running',
                    'Training',
                    'Yoga',
                    'Cricket',
                    'Football',
                    'Badminton',
                    'Cycling',
                    'Gym',
                    'Outdoor',
                ],
            ],
            [
                'name' => 'Weight',
                'code' => 'weight',
                'description' => 'Item weight or equipment weight',
                'values' => [
                    'Lightweight',
                    '500 g',
                    '1 kg',
                    '2 kg',
                    '5 kg',
                    '10 kg',
                    '15 kg',
                    '20 kg',
                    'Heavy',
                ],
            ],
            [
                'name' => 'Language',
                'code' => 'language',
                'description' => 'Book or content language',
                'values' => [
                    'English',
                    'Hindi',
                    'Marathi',
                    'Gujarati',
                    'Tamil',
                    'Telugu',
                    'Kannada',
                    'Bilingual',
                ],
            ],
            [
                'name' => 'Binding',
                'code' => 'binding',
                'description' => 'Book or notebook binding type',
                'values' => [
                    'Paperback',
                    'Hardcover',
                    'Spiral',
                    'Stapled',
                    'Perfect Bound',
                    'Loose Sheets',
                ],
            ],
            [
                'name' => 'Subject',
                'code' => 'subject',
                'description' => 'Academic or book subject',
                'selection_type' => 'multiple',
                'values' => [
                    'English',
                    'Maths',
                    'Science',
                    'History',
                    'Geography',
                    'Computer',
                    'Art',
                    'Commerce',
                    'General Knowledge',
                ],
            ],
            [
                'name' => 'Class Standard',
                'code' => 'class_standard',
                'description' => 'School class or standard',
                'values' => [
                    'Nursery',
                    'KG',
                    'Class 1',
                    'Class 2',
                    'Class 3',
                    'Class 4',
                    'Class 5',
                    'Class 6',
                    'Class 7',
                    'Class 8',
                    'Class 9',
                    'Class 10',
                    'Class 11',
                    'Class 12',
                ],
            ],
        ];

        foreach ($groups as $groupIndex => $group) {
            DB::table('product_attribute_groups')->updateOrInsert(
                ['code' => $group['code']],
                fn (bool $exists) => [
                    'name' => $group['name'],
                    'description' => $group['description'],
                    'selection_type' => $group['selection_type'] ?? 'single',
                    'status' => 'active',
                    'sort_order' => $groupIndex + 1,
                    'updated_at' => $now,
                    ...($exists ? [] : [
                        'uuid' => (string) Str::uuid(),
                        'created_at' => $now,
                    ]),
                ],
            );

            $groupId = (int) DB::table('product_attribute_groups')
                ->where('code', $group['code'])
                ->value('id');

            foreach ($group['values'] as $valueIndex => $name) {
                DB::table('product_attribute_group_values')->updateOrInsert(
                    [
                        'product_attribute_group_id' => $groupId,
                        'code' => Str::slug($name),
                    ],
                    fn (bool $exists) => [
                        'name' => $name,
                        'description' => null,
                        'status' => 'active',
                        'sort_order' => $valueIndex + 1,
                        'updated_at' => $now,
                        ...($exists ? [] : [
                            'uuid' => (string) Str::uuid(),
                            'created_at' => $now,
                        ]),
                    ],
                );
            }
        }

        $this->seedCategoryMappings($now);
    }

    private function seedCategoryMappings(mixed $now): void
    {
        $rootIds = DB::table('product_categories')
            ->whereNull('parent_id')
            ->whereNull('deleted_at')
            ->pluck('id', 'name');

        if ($rootIds->isEmpty()) {
            return;
        }

        $mappingsByRoot = [
            'Apparel' => [
                ['code' => 'color', 'is_required' => true, 'is_variant' => true, 'is_image_attribute' => true],
                ['code' => 'size', 'is_required' => true, 'is_variant' => true],
                ['code' => 'material'],
                ['code' => 'sleeve'],
                ['code' => 'neck'],
                ['code' => 'pattern'],
                ['code' => 'fit'],
                ['code' => 'occasion'],
                ['code' => 'festival'],
                ['code' => 'season'],
                ['code' => 'style'],
                ['code' => 'length'],
                ['code' => 'waist_rise'],
                ['code' => 'closure'],
                ['code' => 'care'],
                ['code' => 'country_of_origin'],
            ],
            'Footwear' => [
                ['code' => 'color'],
                ['code' => 'size'],
                ['code' => 'material'],
                ['code' => 'style'],
                ['code' => 'occasion'],
                ['code' => 'season'],
                ['code' => 'closure'],
                ['code' => 'care'],
                ['code' => 'country_of_origin'],
            ],
            'Mobile & Electronics' => [
                ['code' => 'brand_model'],
                ['code' => 'color'],
                ['code' => 'storage'],
                ['code' => 'ram'],
                ['code' => 'warranty'],
                ['code' => 'connectivity'],
                ['code' => 'pack_size'],
                ['code' => 'country_of_origin'],
            ],
            'Beauty & Cosmetics' => [
                ['code' => 'shade'],
                ['code' => 'skin_type'],
                ['code' => 'finish'],
                ['code' => 'form'],
                ['code' => 'net_quantity'],
                ['code' => 'flavor'],
                ['code' => 'shelf_life'],
                ['code' => 'occasion'],
                ['code' => 'country_of_origin'],
            ],
            'Jewellery & Accessories' => [
                ['code' => 'color'],
                ['code' => 'material'],
                ['code' => 'finish'],
                ['code' => 'style'],
                ['code' => 'occasion'],
                ['code' => 'festival'],
                ['code' => 'closure'],
                ['code' => 'dimensions'],
                ['code' => 'country_of_origin'],
            ],
            'Grocery & Daily Needs' => [
                ['code' => 'net_quantity'],
                ['code' => 'pack_size'],
                ['code' => 'flavor'],
                ['code' => 'diet_type'],
                ['code' => 'shelf_life'],
                ['code' => 'form'],
                ['code' => 'country_of_origin'],
            ],
            'Home & Furniture' => [
                ['code' => 'material'],
                ['code' => 'color'],
                ['code' => 'dimensions'],
                ['code' => 'room_type'],
                ['code' => 'finish'],
                ['code' => 'assembly_required'],
                ['code' => 'style'],
                ['code' => 'care'],
                ['code' => 'country_of_origin'],
            ],
            'Sports & Fitness' => [
                ['code' => 'sport_type'],
                ['code' => 'size'],
                ['code' => 'color'],
                ['code' => 'material'],
                ['code' => 'weight'],
                ['code' => 'style'],
                ['code' => 'season'],
                ['code' => 'warranty'],
                ['code' => 'country_of_origin'],
            ],
            'Books & Stationery' => [
                ['code' => 'language'],
                ['code' => 'binding'],
                ['code' => 'subject'],
                ['code' => 'class_standard'],
                ['code' => 'pack_size'],
                ['code' => 'color'],
                ['code' => 'country_of_origin'],
            ],
        ];

        foreach ($mappingsByRoot as $rootName => $mappings) {
            $rootId = $rootIds[$rootName] ?? null;

            if ($rootId === null) {
                continue;
            }

            foreach ($mappings as $index => $mapping) {
                $groupId = DB::table('product_attribute_groups')
                    ->where('code', $mapping['code'])
                    ->value('id');

                if ($groupId === null) {
                    continue;
                }

                DB::table('product_category_attribute_groups')->updateOrInsert(
                    [
                        'root_product_category_id' => $rootId,
                        'product_attribute_group_id' => $groupId,
                    ],
                    fn (bool $exists) => [
                        'is_required' => $mapping['is_required'] ?? false,
                        'is_variant' => $mapping['is_variant'] ?? false,
                        'is_image_attribute' => $mapping['is_image_attribute'] ?? false,
                        'sort_order' => $index + 1,
                        'updated_at' => $now,
                        ...($exists ? [] : ['created_at' => $now]),
                    ],
                );
            }
        }
    }
}
